---
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml
#
cluster.name: "docker-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1

## Use single node discovery in order to disable production mode and avoid bootstrap checks
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
#
discovery.type: single-node

# There has been lots of unassigned shards
# Set default number of replicas to 0 (see https://discuss.elastic.co/t/setting-default-number-of-replicas-for-new-indexes/47782/4)
# The following setting can be used to get rid of unassigned shards
# PUT /_cluster/settings
# {
#  "transient" : {
#    "cluster.routing.rebalance.enable" : "all"
#  }
# }
index.number_of_replicas: 0
