version: '2'

services:

    grafana:
      container_name: grafana
      image: grafana/grafana:5.4.2
      ports:
        - 3000:3000
      volumes:
        - ./grafana:/var/lib/grafana
      restart: always
      network_mode: "host"
