version: '2'

services:

  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx6g -Xms2g"
    networks:
      - elk
    restart: always

  logstash:
    container_name: logstash
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always

  kibana:
    container_name: kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    image: git.codemen.fi:4567/devops/docker-elk/kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always

  es-metrics:
    container_name: es-metrics
    build: es-metrics
    environment:
      - ES_METRICS_INDEX_NAME=elasticsearch_metrics
      - ES_METRICS_CLUSTER_URL=http://$ELASTICSEARCH_HOST:9200
      - ES_METRICS_MONITORING_CLUSTER_URL=http://$ELASTICSEARCH_HOST:9200
    restart: always
    depends_on:
      - elasticsearch

  curator:
    container_name: curator
    build:
      context: curator/
    image: git.codemen.fi:4567/devops/docker-elk/curator
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      CRON: 0 0 * * *
      CONFIG_FILE: /usr/share/curator/config/curator.yml
      COMMAND: /usr/share/curator/config/delete_log_files_curator.yml
      UNIT_COUNT: 90
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
