---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200

# Elastalert
elastalert-kibana-plugin.serverHost: 10.4.11.76
elastalert-kibana-plugin.serverPort: 3030